# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-05ccedb3-cf3d-4dd8-9e34-567bef8f3264";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-05ccedb3-cf3d-4dd8-9e34-567bef8f3264".device = "/dev/disk/by-uuid/05ccedb3-cf3d-4dd8-9e34-567bef8f3264";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-05ccedb3-cf3d-4dd8-9e34-567bef8f3264";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-05ccedb3-cf3d-4dd8-9e34-567bef8f3264";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6DA3-A760";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-2b5fa35a-0135-4cbd-a5ac-cb81c4dcfac1"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
